Pinturería Acuarela/Models/Color.cs
namespace Pinturería_Acuarela
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Color")]
    public partial class Color
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Color()
        {
            Product = new HashSet<Product>();
        }

        public int id { get; set; }

        [Required(ErrorMessage = "Debes ingresar un nombre")]
        [StringLength(255, ErrorMessage = "Debes ingresar un nombre de menos de 255 caracteres")]
        [RegularExpression(@"^[a-zA-Z\u00C0-\u017F\s.]+$", ErrorMessage = "Ingrese un nombre válido")]
        public string name { get; set; }

        [Required(ErrorMessage = "Debes seleccionar un color")]
        [StringLength(7, ErrorMessage = "Debes seleccionar un color válido")]
        [RegularExpression(@"^#[A-Fa-f0-9]{6}$", ErrorMessage = "Ingrese un código válido")]
        public string rgb_hex_code { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
    }
}

Pinturería Acuarela/Controllers/ColorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing.Drawing2D;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Pinturería_Acuarela;
using Pinturería_Acuarela.Filter;

namespace Pinturería_Acuarela.Controllers
{
    [Admin]
    public class ColorsController : Controller
    {
        private EFModel db = new EFModel();

        // GET: Colors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Colors/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,rgb_hex_code")] Color color)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Color repeted = db.Color.Where(c => c.name.Equals(color.name) || c.rgb_hex_code.Equals(color.rgb_hex_code)).FirstOrDefault();
                    if (repeted != null)
                    {
                        ViewBag.Message = "El color o el nombre ingresado ya existe";
                        ViewBag.Error = 1;
                        return View(color);
                    }
                    db.Color.Add(color);
                    db.SaveChanges();
                    TempData["Message"] = "El color se creó correctamente";
                    return RedirectToAction("Index", "Brands");
                }
                else
                {
                    ViewBag.Message = "El nombre ingresado o el color seleccionado no son válidos";
                    ViewBag.Error = 1;
                    return View(color);
                }
            }
            catch (Exception)
            {
                TempData["Message"] = "Ha ocurrido un error inesperado. No se ha podido cargar el color";
                TempData["Error"] = 2;
                return RedirectToAction("Index", "Brands");
            }
        }

        // GET: Colors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Color color = db.Color.Find(id);
            if (color == null)
            {
                ViewBag.Message = "Ha ocurrido un error. No se ha encontrado el color";
                ViewBag.Error = 1;
                color = new Color();
            }
            return View(color);
        }

        // POST: Colors/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,rgb_hex_code")] Color color_edited)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Color repeted = db.Color.Where(c => (c.name.Equals(color_edited.name) || c.rgb_hex_code.Equals(color_edited.rgb_hex_code)) && !c.id.Equals(color_edited.id)).FirstOrDefault();
                    if (repeted != null)
                    {
                        ViewBag.Message = "El color o el nombre ingresado ya existe";
                        ViewBag.Error = 1;
                        return View(color_edited);
                    }
                    Color color = db.Color.Find(color_edited.id);
                    color.name = color_edited.name;
                    color.rgb_hex_code = color_edited.rgb_hex_code;
                    db.SaveChanges();
                    TempData["Message"] = "El color se editó correctamente";
                    return RedirectToAction("Index", "Brands");
                }
                else
                {
                    ViewBag.Message = "El nombre ingresado no es válido";
                    ViewBag.Error = 1;
                    return View(color_edited);
                }
            }
            catch (Exception)
            {
                TempData["Message"] = "Ha ocurrido un error inesperado. No se ha podido guardar el color";
                TempData["Error"] = 2;
                return RedirectToAction("Index", "Brands");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Pinturería Acuarela/Views/Colors/Create.cshtml
@model Pinturería_Acuarela.Color

@{
    ViewBag.Title = "Colores";
}

<link href="~/Content/notification.css" rel="stylesheet" />

<div class="d-flex align-items-end">
    <a class="btn btn-dark py-2" href="../../Brands"><i class="bi bi-arrow-left"></i></a>
    <div class="d-flex flex-grow-1 justify-content-center me-md-4">
        <h1 class="text-center">Cargar un nuevo color</h1>
    </div>
</div>
<hr class="mb-4" />

@{ if (ViewBag.Message != null)
    {
        <div class="py-3 mb-5 @(ViewBag.Error == 1 ? "containerError1" : "")@(ViewBag.Error == 2 ? "containerError2" : "")@(ViewBag.Error == null ? "onlyMessage" : "")" id="notificationContainer">
            <div class="px-2 d-flex flex-row justify-content-between align-items-center">
                <div id="txtNotification">@ViewBag.Message</div>
                <button id="btnCloseNotification" type="button" aria-label="Cerrar">
                    <svg aria-hidden="true" height="16" viewBox="0 0 16 16" version="1.1" width="16" data-view-component="true" class="octicon octicon-x">
                        <path id="closeSVG" fill="rgb(0,75,180)" class="@(ViewBag.Error == 1 ? "error1" : "") @(ViewBag.Error == 2 ? "error2" : "") @(ViewBag.Error == null ? "onlyMessage" : "")" d="M3.72 3.72a.75.75 0 011.06 0L8 6.94l3.22-3.22a.75.75 0 111.06 1.06L9.06 8l3.22 3.22a.75.75 0 11-1.06 1.06L8 9.06l-3.22 3.22a.75.75 0 01-1.06-1.06L6.94 8 3.72 4.78a.75.75 0 010-1.06z"></path>
                    </svg>
                </button>
            </div>
        </div>
    }
}

<div class="container d-flex justify-content-center p-5 mt-5" id="formContainer">
    @using (Html.BeginForm("Create", "Colors", FormMethod.Post, new { @class = "mx-auto " }))
    {
        @Html.AntiForgeryToken()

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div>
            @Html.LabelFor(model => model.name, "Nombre", htmlAttributes: new { @class = "control-label required" })
            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger mb-4 mt-3" })
        </div>

        <div>
            @Html.LabelFor(model => model.rgb_hex_code, "Color", htmlAttributes: new { @class = "control-label required mt-3" })
            @Html.EditorFor(model => model.rgb_hex_code, new { htmlAttributes = new { @type = "color", @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.rgb_hex_code, "", new { @class = "text-danger" })
        </div>

        <div class="d-flex mt-3">
            <input type="submit" value="Aceptar" class="btn flex-grow-1" style="background-color: yellowgreen" />
        </div>
    }
</div>

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/notification.js"></script>

<style>
    #formContainer {
        -webkit-box-shadow: 0px 0px 36px 8px rgba(194,194,194,1);
        -moz-box-shadow: 0px 0px 36px 8px rgba(194,194,194,1);
        box-shadow: 0px 0px 36px 8px rgba(194,194,194,1);
        max-width: 600px;
        border-radius: 1rem;
    }
</style>

Pinturería Acuarela/Views/Colors/Edit.cshtml
@model Pinturería_Acuarela.Color

@{
    ViewBag.Title = "Marcas";
}

<link href="~/Content/notification.css" rel="stylesheet" />

<div class="d-flex align-items-end">
    <a class="btn btn-dark py-2" href="../../Brands"><i class="bi bi-arrow-left"></i></a>
    <div class="d-flex flex-grow-1 justify-content-center me-md-4">
        <h1 class="text-center">Editar color</h1>
    </div>
</div>
<hr class="mb-4" />

@{ if (ViewBag.Message != null)
    {
        <div class="py-3 mb-5 @(ViewBag.Error == 1 ? "containerError1" : "")@(ViewBag.Error == 2 ? "containerError2" : "")@(ViewBag.Error == null ? "onlyMessage" : "")" id="notificationContainer">
            <div class="px-2 d-flex flex-row justify-content-between align-items-center">
                <div id="txtNotification">@ViewBag.Message</div>
                <button id="btnCloseNotification" type="button" aria-label="Cerrar">
                    <svg aria-hidden="true" height="16" viewBox="0 0 16 16" version="1.1" width="16" data-view-component="true" class="octicon octicon-x">
                        <path id="closeSVG" fill="rgb(0,75,180)" class="@(ViewBag.Error == 1 ? "error1" : "") @(ViewBag.Error == 2 ? "error2" : "") @(ViewBag.Error == null ? "onlyMessage" : "")" d="M3.72 3.72a.75.75 0 011.06 0L8 6.94l3.22-3.22a.75.75 0 111.06 1.06L9.06 8l3.22 3.22a.75.75 0 11-1.06 1.06L8 9.06l-3.22 3.22a.75.75 0 01-1.06-1.06L6.94 8 3.72 4.78a.75.75 0 010-1.06z"></path>
                    </svg>
                </button>
            </div>
        </div>
    }
}

<div class="container d-flex justify-content-center p-5 mt-5" id="formContainer">
    @using (Html.BeginForm("Edit", "Colors", FormMethod.Post, new { @class = "mx-auto " }))
    {
        @Html.AntiForgeryToken()

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div>
            @Html.LabelFor(model => model.name, "Nombre", htmlAttributes: new { @class = "control-label required" })
            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger mb-4 mt-3" })
        </div>

        <div>
            @Html.LabelFor(model => model.rgb_hex_code, "Color", htmlAttributes: new { @class = "control-label required mt-3" })
            @Html.EditorFor(model => model.rgb_hex_code, new { htmlAttributes = new { @type = "color", @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.rgb_hex_code, "", new { @class = "text-danger" })
        </div>

        <div class="d-flex mt-3">
            <input type="submit" value="Aceptar" class="btn flex-grow-1" style="background-color: yellowgreen" />
        </div>
    }
</div>

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/notification.js"></script>

<style>
    #formContainer {
        -webkit-box-shadow: 0px 0px 36px 8px rgba(194,194,194,1);
        -moz-box-shadow: 0px 0px 36px 8px rgba(194,194,194,1);
        box-shadow: 0px 0px 36px 8px rgba(194,194,194,1);
        max-width: 600px;
        border-radius: 1rem;
    }
</style>