Pinturería Acuarela/Models/Sell.cs
namespace Pinturería_Acuarela
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Sell")]
    public partial class Sell
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sell()
        {
            Product_Sell = new HashSet<Product_Sell>();
        }

        public int id { get; set; }

        public DateTime date { get; set; }

        public int id_user { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Sell> Product_Sell { get; set; }

        public virtual User User { get; set; }
    }
}

Pinturería Acuarela/Controllers/SellsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;
using Pinturería_Acuarela;
using Pinturería_Acuarela.Filter;

namespace Pinturería_Acuarela.Controllers
{
    [Security]
    public class SellsController : Controller
    {
        private EFModel db = new EFModel();

        // GET: Sells/Create
        [Employee]
        public ActionResult Create()
        {
            try
            {
                if (TempData.Count == 1)
                {
                    ViewBag.Message = TempData["Message"].ToString();
                }
                else if (TempData.Count == 2)
                {
                    ViewBag.Message = TempData["Message"].ToString();
                    ViewBag.Error = TempData["Error"];
                }
                ViewBag.id_user = new SelectList(db.User, "id", "email");
                ViewBag.id_brand = new SelectList(db.Brand.OrderBy(b => b.name), "id", "name");
                ViewBag.id_category = new SelectList(db.Category.OrderBy(c => c.description), "id", "description");
                ViewBag.id_subcategory = new SelectList(db.Subcategory.OrderBy(s => s.description), "id", "description");
                ViewBag.id_color = new SelectList(db.Color.OrderBy(c => c.name), "id", "name");
                ViewBag.id_capacity = new SelectList(db.Capacity.OrderByDescending(c => c.capacity), "id", "description");
                return View();
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        // GET: Products by filter
        [Employee]
        [HttpGet]
        public JsonResult FilterProducts(string id_brand, string id_category, string id_subcategory, string id_color, string id_capacity)
        {
            try
            {
                if (id_brand == "" && id_category == "" && id_subcategory == "" && id_color == "" && id_capacity == "")
                {
                    return Json(null, JsonRequestBehavior.AllowGet);
                }

                User user = Session["User"] as User;
                int id_business = user.Business.id;

                var products = db.Product
                    .Where(p =>
                    p.Product_Business.Any(pb => pb.id_product.Equals(p.id) && pb.id_business.Equals(id_business) && pb.deleted_at.Equals(null)) &&
                    p.id_brand.ToString().Contains(id_brand) &&
                    p.id_category.ToString().Contains(id_category) &&
                    p.id_subcategory.ToString().Contains(id_subcategory) &&
                    p.id_color.ToString().Contains(id_color) &&
                    p.id_capacity.ToString().Contains(id_capacity) &&
                    p.deleted_at.Equals(null))
                    .Select(p => new
                    {
                        p.internal_code,
                        product_id = p.id.ToString(),
                        p.description,
                        brand = p.Brand.name,
                        category = p.Category.description,
                        subcategory = p.Subcategory.description,
                        color = p.Color.name,
                        p.Color.rgb_hex_code,
                        capacity = p.Capacity.description,
                        stock = p.Product_Business.Where(pb => pb.id_product.Equals(p.id) && pb.id_business.Equals(id_business)).FirstOrDefault().stock.ToString(),
                        minimum_stock = p.Product_Business.Where(pb => pb.id_product.Equals(p.id) && pb.id_business.Equals(id_business)).FirstOrDefault().minimum_stock.ToString()
                    }).ToList();
                return Json(products.ToList(), JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return Json(JsonRequestBehavior.AllowGet);
            }
        }

        // GET: Products by name
        [Employee]
        [HttpGet]
        public JsonResult FilterProductsByName(string name)
        {
            try
            {
                User user = Session["User"] as User;
                int id_business = user.Business.id;

                var products = db.Product
                        .Where(p =>
                        p.Product_Business.Any(pb => pb.id_product.Equals(p.id) && pb.id_business.Equals(id_business) && pb.deleted_at.Equals(null)) &&
                        (p.description.Contains(name) ||
                        p.internal_code.ToString().Contains(name)) &&
                        p.deleted_at.Equals(null))
                        .Select(p => new
                        {
                            p.internal_code,
                            product_id = p.id.ToString(),
                            p.description,
                            brand = p.Brand.name,
                            category = p.Category.description,
                            subcategory = p.Subcategory.description,
                            color = p.Color.name,
                            p.Color.rgb_hex_code,
                            capacity = p.Capacity.description,
                            stock = p.Product_Business.Where(pb => pb.id_product.Equals(p.id) && pb.id_business.Equals(id_business)).FirstOrDefault().stock.ToString(),
                            minimum_stock = p.Product_Business.Where(pb => pb.id_product.Equals(p.id) && pb.id_business.Equals(id_business)).FirstOrDefault().minimum_stock.ToString()
                        }).ToList();

                return Json(products, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return Json(null, JsonRequestBehavior.AllowGet);
            }
        }

        // GET: Add products to cart
        [Employee]
        [HttpGet]
        public ActionResult AddToSale(int? id_prod, int? quant)
        {
            try
            {
                User user = Session["User"] as User;
                List<Product_Sell> sell = new List<Product_Sell>();
                if (id_prod != null && quant != null)
                {
                    if (Session["Sell"] != null)
                    {
                        sell = Session["Sell"] as List<Product_Sell>;
                    }
                    if (quant.Value > 0)
                    {
                        // Check del stock
                        int stock = db.Product_Business.Where(b => b.id_business.Equals(user.id_business.Value) && b.id_product.Equals(id_prod.Value)).FirstOrDefault().stock;

                        Product_Sell prod = new Product_Sell();
                        prod.Product = db.Product
                            .Where(p => p.id.Equals(id_prod.Value))
                            .Include(p => p.Brand)
                            .Include(p => p.Category)
                            .Include(p => p.Subcategory)
                            .Include(p => p.Capacity)
                            .Include(p => p.Product_Business)
                            .First();

                        // Si no hay ningun producto agregado
                        if (sell.Count == 0 && quant.Value <= stock)
                        {
                            prod.quantity = quant.Value;
                            sell.Add(prod);
                            TempData["Message"] = "El producto se agregó correctamente";
                            Session["Sell"] = sell.Count == 0 ? null : sell;
                            return RedirectToAction("Create");
                        }
                        else
                        {
                            int count = sell.Count;
                            for (int index = 0; index < count; index++)
                            {
                                // Si se repite el producto
                                if (sell[index].Product.id == prod.Product.id)
                                {
                                    if (sell[index].quantity + quant.Value <= stock)
                                    {
                                        sell[index].quantity += quant.Value;
                                        TempData["Message"] = "El producto se sumó correctamente";
                                        Session["Sell"] = sell.Count == 0 ? null : sell;
                                        return RedirectToAction("Create");
                                    }
                                    else
                                    {
                                        TempData["Message"] = "No cuentas con stock suficiente";
                                        TempData["Error"] = 1;
                                        return RedirectToAction("Create");
                                    }
                                }
                                // Si no se repite el producto
                                else if (index == sell.Count - 1)
                                {
                                    prod.quantity = quant.Value;
                                    sell.Add(prod);
                                    TempData["Message"] = "El producto se agregó correctamente";
                                    Session["Sell"] = sell.Count == 0 ? null : sell;
                                    return RedirectToAction("Create");
                                }
                            }
                        }
                    }
                    TempData["Message"] = "Por favor, selecciona una cantidad mayor a 0";
                    TempData["Error"] = 1;

Pinturería Acuarela/Views/Sells/Create.cshtml
@model Pinturería_Acuarela.Sell

@{
    Layout = null;
    ViewBag.Title = "Ventas";
    List<Product_Sell> products = Session["Sell"] as List<Product_Sell>;
}


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Pinturería Acuarela</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />

    <link href="~/Content/orders.css" rel="stylesheet" />
    <link href="~/Content/notification.css" rel="stylesheet" />
    <link href="~/Content/table.css" rel="stylesheet" />

    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="icon" type="image/jpg" href="~/Content/Images/favicon.png" />
</head>
<body>
    <main>
        <div id="page-container">
            <div id="content-wrap" class="container-fluid body-content" style="padding: 3rem">
                <div class="d-flex align-items-end">
                    <a class="btn btn-dark py-2" href="../../Home"><i class="bi bi-arrow-left"></i></a>
                    <div class="d-flex flex-grow-1 justify-content-center me-md-4">
                        <h1 class="text-center">Ventas</h1>
                    </div>
                    <div class="d-flex justify-content-between">
                        <a class="btn text-white" href="../../Sells/Details" style="background-color: #6c7ae0">Historial Ventas</a>
                    </div>
                </div>
                <hr class="mb-3" />


                @{ if (ViewBag.Message != null)
                    {
                        <div class="py-3 mb-5 @(ViewBag.Error == 1 ? "containerError1" : "")@(ViewBag.Error == 2 ? "containerError2" : "")@(ViewBag.Error == null ? "onlyMessage" : "")" id="notificationContainer">
                            <div class="px-2 d-flex flex-row justify-content-between align-items-center">
                                <div id="txtNotification">@ViewBag.Message</div>
                                <button id="btnCloseNotification" type="button" aria-label="Cerrar">
                                    <svg aria-hidden="true" height="16" viewBox="0 0 16 16" version="1.1" width="16" data-view-component="true" class="octicon octicon-x">
                                        <path id="closeSVG" fill="rgb(0,75,180)" class="@(ViewBag.Error == 1 ? "error1" : "") @(ViewBag.Error == 2 ? "error2" : "") @(ViewBag.Error == null ? "onlyMessage" : "")" d="M3.72 3.72a.75.75 0 011.06 0L8 6.94l3.22-3.22a.75.75 0 111.06 1.06L9.06 8l3.22 3.22a.75.75 0 11-1.06 1.06L8 9.06l-3.22 3.22a.75.75 0 01-1.06-1.06L6.94 8 3.72 4.78a.75.75 0 010-1.06z"></path>
                                    </svg>
                                </button>
                            </div>
                        </div>
                    }
                }

                @* Filtros *@
                <div class="mb-5 d-flex flex-row">
                    <div class="col-9 me-3">
                        <div class="sombra p-4 mb-5" style="border-radius: 20px">
                            <div class="sombra mb-3 d-flex flex-row" style="max-width: fit-content">
                                <input class="form-control py-2" id="txtSearch" placeholder="Cód. interno | Nombre" />
                                <button id="btnSearch" type="button" class="btn" style="background-color: #6c7ae0">
                                    <i class="bi bi-search" style="color: white"></i>
                                </button>
                            </div>
                            <div class="d-flex flex-row">
                                <div class="col-2">
                                    <label class="text-center">Marca</label>
                                    @Html.DropDownList("id_brand", null, "Seleccionar", htmlAttributes: new { @class = "form-select sombra", @id = "id_brand" })
                                </div>
                                <div class="col-2">
                                    <label class="text-center">Categoría</label>
                                    @Html.DropDownList("id_category", null, "Seleccionar", htmlAttributes: new { @class = "form-select sombra", @id = "id_category" })
                                </div>
                                <div class="col-2">
                                    <label class="text-center">Subcategoría</label>
                                    @Html.DropDownList("id_subcategory", null, "Seleccionar", htmlAttributes: new { @class = "form-select sombra", @id = "id_subcategory" })
                                </div>
                                <div class="col-2">
                                    <label class="text-center">Color</label>
                                    @Html.DropDownList("id_color", null, "Seleccionar", htmlAttributes: new { @class = "form-select sombra", @id = "id_color" })
                                </div>
                                <div class="col-2">
                                    <label class="text-center">Capacidad</label>
                                    @Html.DropDownList("id_capacity", null, "Seleccionar", htmlAttributes: new { @class = "form-select sombra", @id = "id_capacity" })
                                </div>
                                <div class="col-2 d-flex align-items-end">
                                    <button type="button" class="btn" style="background-color: #6c7ae0; padding: 0.7rem 1rem;" id="btnFilter"><i class="bi bi-search" style="color: white"></i></button>
                                </div>
                            </div>
                        </div>

                        @* Tabla *@
                        <div class="table100 ver1 m-b-110">
                            <div class="table100-head">
                                <table>
                                    <thead>
                                        <tr class="row100 head">
                                            <th class="text-center column5 ps-2">Código</th>
                                            <th class="text-center column20">Producto</th>
                                            <th class="text-center column10">Marca</th>
                                            <th class="text-center column10">Categoría</th>
                                            <th class="text-center column10">Subcategoría</th>
                                            <th class="text-center column10">Color</th>
                                            <th class="text-center column10">Capacidad</th>
                                            <th class="text-center column10">Stock</th>
                                            <th class="text-center column20">Cantidad</th>
                                            <th class="text-center column10 pe-3">Agregar</th>
                                        </tr>
                                    </thead>
                                </table>
                            </div>
                            <div class="table100-body js-pscroll ps ps--active-y">
                                <table>
                                    <tbody id="contentTable">

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                    @* Tabla carrito *@
                    <div class="col-3 mx-auto">
                        <div class="table100 ver1">
                            <div class="table100-head">
                                <table>
                                    <thead>
                                        <tr class="row100 head d-flex">
                                            <th class="cell100 py-3 text-center" style="width: 40%; background-color: lightgreen; background-image: linear-gradient(to bottom, transparent, #646464ab); color: rgb(80, 80, 80)">Producto</th>
                                            <th class="cell100 py-3 text-center" style="width: 30%; background-color: lightgreen; background-image: linear-gradient(to bottom, transparent, #646464ab); color: rgb(80, 80, 80) ">Cantidad</th>
                                            <th class="cell100 py-3 text-center" style="width: 30%; background-color: lightgreen; background-image: linear-gradient(to bottom, transparent, #646464ab); color: rgb(80, 80, 80) ">Eliminar</th>
                                        </tr>
                                    </thead>
                                </table>
                            </div>
                            <div class="table100-body js-pscroll ps ps--active-y">
                                <table>
                                    <tbody id="contentTable">
                                        @if (products != null)
                                        {
                                            foreach (Product_Sell item in products.OrderByDescending(p => p.quantity))
                                            {
                                                <tr class="row100 body d-flex">
                                                    <td class="cell100 ms-3 ms-xl-1" style="width: 40%">@Html.DisplayFor(modelItem => item.Product.description)</td>
                                                    <td class="cell100 text-center" style="width: 30%">@Html.DisplayFor(modelItem => item.quantity)</td>
                                                    <td class="cell100 text-center" style="width: 30%">
                                                        @using (Html.BeginForm("RemoveProductSell", "Sells", FormMethod.Post))
                                                        {
                                                            @Html.AntiForgeryToken()
                                                            @Html.Hidden("id_prod", item.Product.id)
                                                            <button class="btn" style="background-color: #ff5969; color: white; padding: 0.2rem 0.5rem" type="submit"><i class='bi bi-x-lg'></i></button>
                                                        }
                                                    </td>
                                                </tr>
                                            }
                                            <tr>
                                                @using (Html.BeginForm("ConfirmSale", "Sells", FormMethod.Post))
                                                {
                                                    @Html.AntiForgeryToken()
                                                    <td class="cell100 d-flex justify-content-end pe-3">
                                                        <button class="btn" style="background-color: lightgreen; color: rgb(80, 80, 80); text-shadow: 0px 0px 30px #000;" type="submit">Confirmar</button>
                                                    </td>
                                                }
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
                <br />
            </div>
        </div>
    </main>

    <footer id="footer" class="text-center bg-dark text-white d-flex align-items-center justify-content-center" style="padding-left: 0">
        <p id="footerText" class="m-0 text-center px-3" style="font-size: 1.1rem; color: rgba(255, 255, 255, 0.8);">Pinturería Acuarela - Todos los derechos reservados @DateTime.UtcNow.AddHours(-3).Year &copy; </p>
    </footer>

    <script src="~/Scripts/jquery-3.6.3.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    <script src="~/Scripts/sale.js"></script>
    <script src="~/Scripts/notification.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"></script>
</body>
</html>

Pinturería Acuarela/Views/Sells/Details.cshtml
@model IEnumerable<Pinturería_Acuarela.Sell>

@{
    ViewBag.Title = "Historial de Ventas";
}

<link href="~/Content/datatables.css" rel="stylesheet" />
<link href="~/Content/orders.css" rel="stylesheet" />
<link href="~/Content/notification.css" rel="stylesheet" />
<link href="~/Content/daterangepicker.css" rel="stylesheet" />

<div class="d-flex align-items-end">
    <a class="btn btn-dark py-2" href="../../Sells/Create"><i class="bi bi-arrow-left"></i></a>
    <div class="d-flex flex-grow-1 justify-content-center me-md-4">
        <h1 class="text-center">Historial de ventas</h1>
    </div>
</div>
<hr class="mb-3" />

@{ if (ViewBag.Message != null)
    {
        <div class="py-3 mb-5 @(ViewBag.Error == 1 ? "containerError1" : "")@(ViewBag.Error == 2 ? "containerError2" : "")@(ViewBag.Error == null ? "onlyMessage" : "")" id="notificationContainer">
            <div class="px-2 d-flex flex-row justify-content-between align-items-center">
                <div id="txtNotification">@ViewBag.Message</div>
                <button id="btnCloseNotification" type="button" aria-label="Cerrar">
                    <svg aria-hidden="true" height="16" viewBox="0 0 16 16" version="1.1" width="16" data-view-component="true" class="octicon octicon-x">
                        <path id="closeSVG" fill="rgb(0,75,180)" class="@(ViewBag.Error == 1 ? "error1" : "") @(ViewBag.Error == 2 ? "error2" : "") @(ViewBag.Error == null ? "onlyMessage" : "")" d="M3.72 3.72a.75.75 0 011.06 0L8 6.94l3.22-3.22a.75.75 0 111.06 1.06L9.06 8l3.22 3.22a.75.75 0 11-1.06 1.06L8 9.06l-3.22 3.22a.75.75 0 01-1.06-1.06L6.94 8 3.72 4.78a.75.75 0 010-1.06z"></path>
                    </svg>
                </button>
            </div>
        </div>
    }
}

@* Input fecha *@
<div class="sombra p-4 mb-4 mx-auto d-flex justify-content-center" style="border-radius: 20px; max-width: fit-content">
    <div id="searchContainer" class="d-flex justify-content-center">
        <div class="d-flex flex-column">
            <label for="datepicker" class="form-label">Intervalo de fechas:</label>
            <input type="text" class="form-control py-2" id="datepicker" readonly placeholder="dd/mm/aaaa" />
        </div>
    </div>
</div>

@* Tabla *@
<div id="tableContainer" class="pt-4 container">

</div>


<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/moment-with-locales.js"></script>
<script src="~/Scripts/daterangepicker.js"></script>
<script src="~/Scripts/notification.js"></script>
<script src="~/Scripts/datatables.js"></script>
<script src="~/Scripts/saledetails.js"></script>

<style>
    .clickable-row:hover {
        cursor: pointer;
        background-color: aliceblue;
    }
</style>

Pinturería Acuarela/Views/Sells/DetailsSale.cshtml
@model List<Product_Sell>

@{
    ViewBag.Title = "Detalle venta";
}


<div class="d-flex align-items-end">
    <a class="btn btn-dark py-2" href="../../Sells/Details"><i class="bi bi-arrow-left"></i></a>
    <div class="d-flex flex-grow-1 justify-content-center me-md-4">
        <h1 class="text-center">Detalles de la venta</h1>
    </div>
</div>
<hr class="mb-4" />

<div>
    <table class="table">
        <tr>
            <th>
                Código interno
            </th>
            <th>
                Descripción
            </th>
            <th>
                Marca
            </th>
            <th>
                Categoría
            </th>
            <th>
                Subcategoría
            </th>
            <th>
                Cantidad
            </th>
        </tr>
            @foreach (Product_Sell item in Model)
            {
            <tr>
                <td>
                    @(item.Product.internal_code != null ? item.Product.internal_code.ToString() : "-")
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.Brand.name)
                </td>
                <td>
                    @(item.Product.id_category != null ? item.Product.Category.description : "-")
                </td>
                <td>
                    @(item.Product.id_subcategory != null ? item.Product.Subcategory.description : "-")
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.quantity)
                </td>
            </tr>
            }
        </table>
</div>

Pinturería Acuarela/Views/Sells/Stats.cshtml
@{
    ViewBag.Title = "Gastos";
}

<link href="~/Content/orders.css" rel="stylesheet" />
<link href="~/Content/notification.css" rel="stylesheet" />
<link href="~/Content/table.css" rel="stylesheet" />
<link href="~/Content/daterangepicker.css" rel="stylesheet" />

<h1 class="text-center">Estadísticas</h1>
<hr class="mb-3" />


<div class="mb-5 d-flex flex-row">
    <div class="col-xl-9 col-11 mx-auto">

        @* Input fecha *@
        <div class="sombra p-4 mb-4 mx-auto d-flex justify-content-center" style="border-radius: 20px; max-width: fit-content">
            <div id="searchContainer" class="d-flex justify-content-center">
                <div class="d-flex flex-column">
                    <label for="datepicker" class="form-label">Intervalo de fechas:</label>
                    <input type="text" class="form-control py-2" id="datepicker" readonly placeholder="dd/mm/aaaa" />
                </div>
            </div>
        </div>


        @* Tabla *@
        <div id="tablesContainer">

        </div>
    </div>
</div>

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/moment-with-locales.js"></script>
<script src="~/Scripts/daterangepicker.js"></script>
<script src="~/Scripts/stats.js"></script>
<script src="~/Scripts/notification.js"></script>