Pinturería Acuarela/Models/Brand.cs
namespace Pinturería_Acuarela
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Brand")]
    public partial class Brand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Brand()
        {
            Product = new HashSet<Product>();
        }

        public int id { get; set; }

        [Required(ErrorMessage = "Debes ingresar un nombre")]
        [StringLength(255, ErrorMessage = "Debes ingresar un nombre de menos de 255 caracteres")]
        [RegularExpression(@"^[a-zA-Z\u00C0-\u017F\s'0-9.]+$", ErrorMessage = "Ingrese un nombre válido")]
        public string name { get; set; }

        public DateTime created_at { get; set; }

        public DateTime? deleted_at { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
    }
}

Pinturería Acuarela/Controllers/BrandsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Pinturería_Acuarela;
using Pinturería_Acuarela.Filter;

namespace Pinturería_Acuarela.Controllers
{
    [Admin]
    public class BrandsController : Controller
    {
        private EFModel db = new EFModel();

        // GET: Brands
        public ActionResult Index()
        {
            try
            {
                if (TempData.Count == 1)
                {
                    ViewBag.Message = TempData["Message"].ToString();
                }
                else if (TempData.Count == 2)
                {
                    ViewBag.Message = TempData["Message"].ToString();
                    ViewBag.Error = TempData["Error"];
                }
                var brands = db.Brand.Where(b => b.deleted_at.Equals(null)).ToList();
                var colors = db.Color.ToList();

                Tuple<List<Brand>, List<Color>> model = new Tuple<List<Brand>, List<Color>>(brands, colors);

                return View(model);
            }
            catch (Exception)
            {
                return RedirectToAction("Index", "Home");
            }
        }

        // GET: Brands/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Brands/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name")] Brand brand)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Brand repeted = db.Brand.Where(b => b.name.Equals(brand.name)).FirstOrDefault();
                    if (repeted != null)
                    {
                        ViewBag.Message = "La marca ingresada ya existe";
                        ViewBag.Error = 1;
                        return View(brand);
                    }
                    brand.created_at = DateTime.UtcNow.AddHours(-3);
                    db.Brand.Add(brand);
                    db.SaveChanges();
                    TempData["Message"] = "La marca se creó correctamente";
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Message = "El nombre ingresado no es válido";
                    ViewBag.Error = 1;
                    return View(brand);
                }
            }
            catch (Exception)
            {
                TempData["Message"] = "Ha ocurrido un error inesperado. No se ha podido cargar la marca";
                TempData["Error"] = 2;
                return RedirectToAction("Index");
            }
        }

        // GET: Brands/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = db.Brand.Find(id);
            if (brand == null)
            {
                ViewBag.Message = "Ha ocurrido un error. No se ha encontrado la marca";
                ViewBag.Error = 1;
                brand = new Brand();
            }
            return View(brand);
        }

        // POST: Brands/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name")] Brand brand_edited)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Brand repeted = db.Brand.Where(b => b.name.Equals(brand_edited.name) && !b.id.Equals(brand_edited.id)).FirstOrDefault();
                    if (repeted != null)
                    {
                        ViewBag.Message = "La marca ingresada ya existe";
                        ViewBag.Error = 1;
                        return View(brand_edited);
                    }
                    Brand brand = db.Brand.Find(brand_edited.id);
                    brand.name = brand_edited.name;
                    db.SaveChanges();
                    TempData["Message"] = "La marca se editó correctamente";
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Message = "El nombre ingresado no es válido";
                    ViewBag.Error = 1;
                    return View(brand_edited);
                }
            }
            catch (Exception)
            {
                TempData["Message"] = "Ha ocurrido un error inesperado. No se ha podido guardar la marca";
                TempData["Error"] = 2;
                return RedirectToAction("Index");
            }
        }

        // POST: Brands/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id_brand)
        {
            try
            {
                Brand brand = db.Brand.Find(id_brand);
                if (brand != null)
                {
                    brand.deleted_at = DateTime.UtcNow.AddHours(-3);
                    db.SaveChanges();
                    TempData["Message"] = "La marca fue eliminada";
                    return RedirectToAction("Index");
                } else
                {
                    TempData["Message"] = "Ha ocurrido un error. No se ha encontrado la marca";
                    TempData["Error"] = 1;
                    return RedirectToAction("Index");
                }
            }
            catch (Exception)
            {
                TempData["Message"] = "Ha ocurrido un error inesperado. No se ha podido eliminar la marca";
                TempData["Error"] = 2;
                return RedirectToAction("Index");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Pinturería Acuarela/Views/Brands/Create.cshtml
@model Pinturería_Acuarela.Brand

@{
    ViewBag.Title = "Marcas";
}

<link href="~/Content/notification.css" rel="stylesheet" />

<div class="d-flex align-items-end">
    <a class="btn btn-dark py-2" href="../../Brands"><i class="bi bi-arrow-left"></i></a>
    <div class="d-flex flex-grow-1 justify-content-center me-md-4">
        <h1 class="text-center">Cargar una nueva marca</h1>
    </div>
</div>
<hr class="mb-4" />

@{ if (ViewBag.Message != null)
    {
        <div class="py-3 mb-5 @(ViewBag.Error == 1 ? "containerError1" : "")@(ViewBag.Error == 2 ? "containerError2" : "")@(ViewBag.Error == null ? "onlyMessage" : "")" id="notificationContainer">
            <div class="px-2 d-flex flex-row justify-content-between align-items-center">
                <div id="txtNotification">@ViewBag.Message</div>
                <button id="btnCloseNotification" type="button" aria-label="Cerrar">
                    <svg aria-hidden="true" height="16" viewBox="0 0 16 16" version="1.1" width="16" data-view-component="true" class="octicon octicon-x">
                        <path id="closeSVG" fill="rgb(0,75,180)" class="@(ViewBag.Error == 1 ? "error1" : "") @(ViewBag.Error == 2 ? "error2" : "") @(ViewBag.Error == null ? "onlyMessage" : "")" d="M3.72 3.72a.75.75 0 011.06 0L8 6.94l3.22-3.22a.75.75 0 111.06 1.06L9.06 8l3.22 3.22a.75.75 0 11-1.06 1.06L8 9.06l-3.22 3.22a.75.75 0 01-1.06-1.06L6.94 8 3.72 4.78a.75.75 0 010-1.06z"></path>
                    </svg>
                </button>
            </div>
        </div>
    }
}

<div class="container d-flex justify-content-center p-5 mt-5" id="formContainer">
    @using (Html.BeginForm("Create", "Brands", FormMethod.Post, new { @class = "mx-auto " }))
    {
        @Html.AntiForgeryToken()

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div>
            @Html.LabelFor(model => model.name, "Nombre", htmlAttributes: new { @class = "control-label required" })
            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger mb-4 mt-3" })
        </div>

        <div class="d-flex mt-3">
            <input type="submit" value="Aceptar" class="btn flex-grow-1" style="background-color: yellowgreen" />
        </div>
    }
</div>

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/notification.js"></script>

<style>
    #formContainer {
        -webkit-box-shadow: 0px 0px 36px 8px rgba(194,194,194,1);
        -moz-box-shadow: 0px 0px 36px 8px rgba(194,194,194,1);
        box-shadow: 0px 0px 36px 8px rgba(194,194,194,1);
        max-width: 600px;
        border-radius: 1rem;
    }
</style>

Pinturería Acuarela/Views/Brands/Edit.cshtml
@model Pinturería_Acuarela.Brand

@{
    ViewBag.Title = "Marcas";
}

<link href="~/Content/notification.css" rel="stylesheet" />

<div class="d-flex align-items-end">
    <a class="btn btn-dark py-2" href="../../Brands"><i class="bi bi-arrow-left"></i></a>
    <div class="d-flex flex-grow-1 justify-content-center me-md-4">
        <h1 class="text-center">Editar marca</h1>
    </div>
</div>
<hr class="mb-4" />

@{ if (ViewBag.Message != null)
    {
        <div class="py-3 mb-5 @(ViewBag.Error == 1 ? "containerError1" : "")@(ViewBag.Error == 2 ? "containerError2" : "")@(ViewBag.Error == null ? "onlyMessage" : "")" id="notificationContainer">
            <div class="px-2 d-flex flex-row justify-content-between align-items-center">
                <div id="txtNotification">@ViewBag.Message</div>
                <button id="btnCloseNotification" type="button" aria-label="Cerrar">
                    <svg aria-hidden="true" height="16" viewBox="0 0 16 16" version="1.1" width="16" data-view-component="true" class="octicon octicon-x">
                        <path id="closeSVG" fill="rgb(0,75,180)" class="@(ViewBag.Error == 1 ? "error1" : "") @(ViewBag.Error == 2 ? "error2" : "") @(ViewBag.Error == null ? "onlyMessage" : "")" d="M3.72 3.72a.75.75 0 011.06 0L8 6.94l3.22-3.22a.75.75 0 111.06 1.06L9.06 8l3.22 3.22a.75.75 0 11-1.06 1.06L8 9.06l-3.22 3.22a.75.75 0 01-1.06-1.06L6.94 8 3.72 4.78a.75.75 0 010-1.06z"></path>
                    </svg>
                </button>
            </div>
        </div>
    }
}

<div class="container d-flex justify-content-center p-5 mt-5" id="formContainer">
    @using (Html.BeginForm("Edit", "Brands", FormMethod.Post, new { @class = "mx-auto " }))
    {
        @Html.AntiForgeryToken()

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div>
            @Html.LabelFor(model => model.name, "Nombre", htmlAttributes: new { @class = "control-label required" })
            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger mb-4 mt-3" })
        </div>

        <div class="d-flex mt-3">
            <input type="submit" value="Aceptar" class="btn flex-grow-1" style="background-color: yellowgreen" />
        </div>
    }
</div>

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/notification.js"></script>

<style>
    #formContainer {
        -webkit-box-shadow: 0px 0px 36px 8px rgba(194,194,194,1);
        -moz-box-shadow: 0px 0px 36px 8px rgba(194,194,194,1);
        box-shadow: 0px 0px 36px 8px rgba(194,194,194,1);
        max-width: 600px;
        border-radius: 1rem;
    }
</style>

Pinturería Acuarela/Views/Brands/Index.cshtml
@{
    ViewBag.Title = "Marcas";
}

@model Tuple<List<Brand>, List<Color>>

<link href="~/Content/notification.css" rel="stylesheet" />

@using (Html.BeginForm("Delete", "Brands", FormMethod.Post))
{
    @Html.AntiForgeryToken();
    @Html.Hidden("id_brand")
    <!-- Modal -->
    <div class="modal fade" id="modalConfirmation" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="modalConfirmationLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="modalConfirmationLabel">Eliminar marca</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
                </div>
                <div class="modal-body">
                    ¿Seguro deseas eliminar esta marca?
                </div>
                <div class="modal-footer d-flex justify-content-between justify-content-lg-end px-3">
                    <button type="submit" id="btnSendForm" class="btn me-lg-4" style="background-color: yellowgreen">Confirmar</button>
                    <button type="button" class="btn" style="background-color: crimson; color: white" data-bs-dismiss="modal">Cancelar</button>
                </div>
            </div>
        </div>
    </div>
}

<h1 class="text-center">Editar</h1>
<hr class="pb-3" />

@{ if (ViewBag.Message != null)
    {
        <div class="py-3 mb-5 @(ViewBag.Error == 1 ? "containerError1" : "")@(ViewBag.Error == 2 ? "containerError2" : "")@(ViewBag.Error == null ? "onlyMessage" : "")" id="notificationContainer">
            <div class="px-2 d-flex flex-row justify-content-between align-items-center">
                <div id="txtNotification">@ViewBag.Message</div>
                <button id="btnCloseNotification" type="button" aria-label="Cerrar">
                    <svg aria-hidden="true" height="16" viewBox="0 0 16 16" version="1.1" width="16" data-view-component="true" class="octicon octicon-x">
                        <path id="closeSVG" fill="rgb(0,75,180)" class="@(ViewBag.Error == 1 ? "error1" : "") @(ViewBag.Error == 2 ? "error2" : "") @(ViewBag.Error == null ? "onlyMessage" : "")" d="M3.72 3.72a.75.75 0 011.06 0L8 6.94l3.22-3.22a.75.75 0 111.06 1.06L9.06 8l3.22 3.22a.75.75 0 11-1.06 1.06L8 9.06l-3.22 3.22a.75.75 0 01-1.06-1.06L6.94 8 3.72 4.78a.75.75 0 010-1.06z"></path>
                    </svg>
                </button>
            </div>
        </div>
    }
}

<div class="container">
    <div class="d-flex flex-row justify-content-between">
        @* Cargar nueva marca *@
        <div class="sombra p-4 mb-3" style="border-radius: 20px; max-width: fit-content">
            <div class="d-flex justify-content-between">
                <a class="btn text-white me-3" href="../../Brands/Create" style="background-color: #6c7ae0">Agregar marca <i class="bi bi-plus-circle"></i></a>
            </div>
        </div>

        @* Cargar nuevo color*@
        <div class="sombra p-4 mb-3" style="border-radius: 20px; max-width: fit-content">
            <div class="d-flex justify-content-between">
                <a class="btn text-white me-3" href="../../Colors/Create" style="background-color: #6c7ae0">Agregar color <i class="bi bi-plus-circle"></i></a>
            </div>
        </div>
    </div>

    <div class="d-flex flex-row">
        
        @* Tabla marcas *@
        <div class="w-50 me-5">
            <h2 class="text-start">Marcas</h2>
            <table class="table">
                <tr>
                    <th>
                        Nombre
                    </th>
                    <th class="text-center">
                        Acción
                    </th>
                </tr>

                @foreach (Brand item in Model.Item1)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.name)
                        </td>
                        <td class="d-flex justify-content-center">
                            <a class="btn me-4" style="background-color: yellowgreen" href="../../Brands/Edit/@item.id"><i class='bi bi-pencil-square'></i></a>
                            <button onclick="setDeleteID(@item.id)" class="btn text-white ms-4" style="background-color: crimson" type="button" data-bs-toggle="modal" data-bs-target="#modalConfirmation"><i class='bi bi-trash3'></i></button>
                        </td>
                    </tr>
                }
            </table>
        </div>
        
        @* Tabla colores *@
        <div class="w-50">
            <h2 class="text-start">Colores</h2>
            <table class="table">
                <tr>
                    <th>
                        Nombre
                    </th>
                    <th>
                        Color
                    </th>
                    <th class="text-center">
                        Acción
                    </th>
                </tr>

                @foreach (Color item in Model.Item2)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.name)
                        </td>
                        <td class="d-flex justify-content-center">
                            <a class="btn" style="background-color: yellowgreen" href="../../Colors/Edit/@item.id"><i class='bi bi-pencil-square'></i></a>
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>
</div>

<script src="~/Scripts/notification.js"></script>
<script>
    function setDeleteID(id) {
        $("#id_brand").val(id);
    };
</script>