Pinturería Acuarela/Controllers/Product_BusinessController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;
using Pinturería_Acuarela;
using Pinturería_Acuarela.Filter;

namespace Pinturería_Acuarela.Controllers
{
    [Security]
    public class Product_BusinessController : Controller
    {
        private EFModel db = new EFModel();

        // GET: Product_Business
        public ActionResult Index(int? id)
        {
            try
            {
                User user = Session["User"] as User;
                if (id == null)
                {
                    id = user.Business.id;
                }

                id = user.Rol.id != 1 ? user.Business.id : id;

                if (TempData.Count == 1)
                {
                    ViewBag.Message = TempData["Message"].ToString();
                }
                else if (TempData.Count == 2)
                {
                    ViewBag.Message = TempData["Message"].ToString();
                    ViewBag.Error = TempData["Error"];
                }

                ViewBag.id_brand = new SelectList(db.Brand.Where(b => b.deleted_at.Equals(null)).OrderBy(b => b.name), "id", "name");
                ViewBag.id_capacity = new SelectList(db.Capacity, "id", "description");
                ViewBag.id_category = new SelectList(db.Category, "id", "description");
                ViewBag.id_color = new SelectList(db.Color, "id", "name");
                ViewBag.id_subcategory = new SelectList(db.Subcategory, "id", "description");
                return View(new Product_Business { Business = db.Business.Find(id.Value) });
            }
            catch (Exception)
            {
                return RedirectToAction(Session["User"].ToString() == "1" ? "AdminIndex" : "Index", "Home");
            }
        }

        // GET: Product_Business/Create
        public ActionResult Create(int? id)
        {
            try
            {
                User user = Session["User"] as User;
                if (id == null)
                {
                    id = user.Business.id;
                }

                id = user.Rol.id != 1 ? user.Business.id : id;

                if (TempData.Count == 1)
                {
                    ViewBag.Message = TempData["Message"].ToString();
                }
                else if (TempData.Count == 2)
                {
                    ViewBag.Message = TempData["Message"].ToString();
                    ViewBag.Error = TempData["Error"];
                }

                ViewBag.id_brand = new SelectList(db.Brand.Where(b => b.deleted_at.Equals(null)).OrderBy(b => b.name), "id", "name");
                ViewBag.id_capacity = new SelectList(db.Capacity, "id", "description");
                ViewBag.id_category = new SelectList(db.Category, "id", "description");
                ViewBag.id_color = new SelectList(db.Color, "id", "name");
                ViewBag.id_subcategory = new SelectList(db.Subcategory, "id", "description");
                
                return View(new Product_Business { Business = db.Business.Find(id.Value) });
            }
            catch (Exception)
            {
                return RedirectToAction(Session["User"].ToString() == "1" ? "AdminIndex" : "Index", "Home");
            }
        }

        // POST: Product_Business/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_product,id_business,minimum_stock,stock")] Product_Business product_Business)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    product_Business.created_at = DateTime.UtcNow.AddHours(-3);
                    db.Product_Business.Add(product_Business);
                    db.SaveChanges();
                    TempData["Message"] = "Producto añadido correctamente";
                }
                return RedirectToAction("Index", new { id = product_Business.id_business });
            }
            catch (Exception)
            {
                TempData["Message"] = "Ha ocurrido un error inesperado. No se ha podido añadir el producto";
                TempData["Error"] = 2;
                return RedirectToAction(Session["User"].ToString() == "1" ? "AdminIndex" : "Index", "Home");
            }

        }

        // POST: Product_Business/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_product,id_business,minimum_stock,stock")] Product_Business stock_updated)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Product_Business product_Business = db.Product_Business.Find(stock_updated.id_product, stock_updated.id_business);
                    product_Business.stock = stock_updated.stock;
                    product_Business.minimum_stock = stock_updated.minimum_stock;
                    db.SaveChanges();
                    TempData["Message"] = "Stock actualizado correctamente";
                }
                return RedirectToAction("Index", new { id = stock_updated.id_business });
            }
            catch (Exception)
            {
                TempData["Message"] = "Ha ocurrido un error inesperado. No se ha podido actualizar el stock";
                TempData["Error"] = 2;
                return RedirectToAction(Session["User"].ToString() == "1" ? "AdminIndex" : "Index", "Home");
            }
        }

        // POST: Product_Business/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id_product_delete, int id_business_delete)
        {
            try
            {
                Product_Business product_Business = db.Product_Business.Where(pb => pb.id_product.Equals(id_product_delete) && pb.id_business.Equals(id_business_delete)).FirstOrDefault();
                if (product_Business != null)
                {
                    product_Business.deleted_at = DateTime.UtcNow.AddHours(-3);
                    db.SaveChanges();
                    TempData["Message"] = "Producto desasociado correctamente";
                    return RedirectToAction("Index", new { id = product_Business.id_business });
                }
                TempData["Error"] = 1;
                TempData["Message"] = "Ha ocurrido un error. No se ha podido encontrar el producto";
                return RedirectToAction("Index", new { id = id_business_delete });

            }
            catch (Exception)
            {
                TempData["Message"] = "Ha ocurrido un error inesperado. No se ha podido desasociar el producto";
                TempData["Error"] = 2;
                return RedirectToAction(Session["User"].ToString() == "1" ? "AdminIndex" : "Index", "Home");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        // GET: Products by filter
        [HttpGet]
        public JsonResult FilterProducts(string id_brand, string id_category, string id_subcategory, string id_color, string id_capacity, int? id_business)
        {
            try
            {
                if (id_brand == "" && id_category == "" && id_subcategory == "" && id_color == "" && id_capacity == "")
                {
                    return Json(null, JsonRequestBehavior.AllowGet);
                }

                User user = Session["User"] as User;
                if (id_business == null)
                {
                    id_business = user.Business.id;
                }

                id_business = user.Rol.id != 1 ? user.Business.id : id_business;

                var products_in_business = db.Product
                        .Where(p =>
                        p.Product_Business.Any(pb => pb.id_product.Equals(p.id) && pb.id_business.Equals(id_business.Value)) &&
                        p.Brand.deleted_at.Equals(null) &&
                        p.deleted_at.Equals(null));

                var products_not_in_business = db.Product
                    .Except(products_in_business)
                .Where(p =>
                    p.id_brand.ToString().Contains(id_brand) &&
                    p.id_category.ToString().Contains(id_category) &&
                    p.id_subcategory.ToString().Contains(id_subcategory) &&
                    p.id_color.ToString().Contains(id_color) &&
                    p.id_capacity.ToString().Contains(id_capacity) &&
                    p.Brand.deleted_at.Equals(null) &&
                    p.deleted_at.Equals(null));

                var response = products_not_in_business.Select(p => new
                {
                    p.internal_code,
                    product_id = p.id.ToString(),
                    p.description,
                    brand = p.Brand.name,
                    category = p.Category.description,
                    subcategory = p.Subcategory.description,
                    color = p.Color.name,
                    p.Color.rgb_hex_code,
                    capacity = p.Capacity.description,
                }).ToList();

                return Json(response, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return Json(null, JsonRequestBehavior.AllowGet);
            }

Pinturería Acuarela/Views/Product_Business/Create.cshtml
@model Pinturería_Acuarela.Product_Business

@{
    ViewBag.Title = "Stock";
}

<link href="~/Content/orders.css" rel="stylesheet" />

<div class="d-flex align-items-end">
    <a class="btn btn-dark py-2" href="../../Product_Business/Index/@Model.Business.id"><i class="bi bi-arrow-left"></i></a>
    <div class="d-flex flex-grow-1 justify-content-center me-md-4">
        <h1 class="text-center">Asociar un producto a @Model.Business.adress</h1>
    </div>
</div>
<hr class="mb-4" />

@using (Html.BeginForm("Create", "Product_Business", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.Hidden("id_product")
    @Html.Hidden("id_business", Model.Business.id)
    <!-- Modal -->
    <div class="modal modal-lg" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Cargar stock</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
                </div>
                <div class="modal-body d-flex flex-column">
                    <div class="d-flex flex-column">
                        <div class="d-flex flex-row justify-content-center align-items-center">
                            <label class="pe-3">Stock existente: </label>
                            <div class='d-flex flex-row justify-content-center ps-3'>
                                <div class='value-button' id='decrease_stock' onclick='decreaseValue("stock")' value='Decrease Value'>-</div>
                                @Html.TextBoxFor(model => model.stock, null, new { @type = "number", @id = "stock", @class = "number" })
                                <div class='value-button' id='increase_stock' onclick='increaseValue("stock")' value='Increase Value'>+</div>
                            </div>
                        </div>
                        @Html.ValidationMessageFor(model => model.stock, null, new { @class = "text-center text-danger mb-4" })
                    </div>
                    <div class="d-flex flex-column">
                        <div class="d-flex flex-row justify-content-center align-items-center">
                            <label class="pe-3">Stock mínimo: </label>
                            <div class='d-flex flex-row justify-content-center ps-3'>
                                <div class='value-button' id='decrease_minimum_stock' onclick='decreaseValue("minimum_stock")' value='Decrease Value'>-</div>
                                @Html.TextBoxFor(model => model.minimum_stock, null, new { @type = "number", @id = "minimum_stock", @class = "number" })
                                <div class='value-button' id='increase_minimum_stock' onclick='increaseValue("minimum_stock")' value='Increase Value'>+</div>
                            </div>
                        </div>
                        @Html.ValidationMessageFor(model => model.minimum_stock, null, new { @class = "text-center text-danger mb-4" })
                    </div>
                </div>
                <div class="modal-footer">
                    <button id="btnSendForm" type="submit" class="btn btn-primary">Cargar stock</button>
                    <button id="modalCerrar" type="button" class="btn btn-danger" data-bs-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
}


<div class="container mt-4">
    <table id='dataTable' class='container table table-light table-striped table-bordered table-hover pt-4' style="border-color: rgb(80, 80, 80, 0.41)">
        <thead class="table-purple">
            <tr>
                <td class='text-center sombra'></td>
                <td class='text-center d-flex flex-row sombra'>
                    <input class="form-control" id="txtSearch" placeholder="Cód. interno | Nombre" />
                    <button id="btnSearch" type="button" class="btn" style="color: white; background-color: #6c7ae0">
                        <i class="bi bi-search"></i>
                    </button>
                </td>
                <td class='text-center sombra'>@Html.DropDownList("id_brand", null, "Seleccionar", htmlAttributes: new { @class = "form-control", @id = "id_brand" })</td>
                <td class='text-center sombra'>@Html.DropDownList("id_category", null, "Seleccionar", htmlAttributes: new { @class = "form-control", @id = "id_category" })</td>
                <td class='text-center sombra'>@Html.DropDownList("id_subcategory", null, "Seleccionar", htmlAttributes: new { @class = "form-control", @id = "id_subcategory" })</td>
                <td class='text-center sombra'>@Html.DropDownList("id_color", null, "Seleccionar", htmlAttributes: new { @class = "form-control", @id = "id_color" })</td>
                <td class='text-center sombra'>@Html.DropDownList("id_capacity", null, "Seleccionar", htmlAttributes: new { @class = "form-control", @id = "id_capacity" })</td>
                <td class='text-center sombra'><input type="button" value="Filtrar" class="btn btn-outline-light" id="btnFilter" /></td>
            </tr>
            <tr>
                <td class='text-center sombra'>Cód. Interno</td>
                <td class='text-center sombra'>Producto</td>
                <td class='text-center sombra'>Marca</td>
                <td class='text-center sombra'>Categoría</td>
                <td class='text-center sombra'>Subcategoría</td>
                <td class='text-center sombra'>Color</td>
                <td class='text-center sombra'>Capacidad</td>
                <td class='text-center sombra'>Añadir</td>
            </tr>
        </thead>
        <tbody id="contentTable" class="sombra">
        </tbody>
    </table>
</div>

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/product_business_create.js"></script>

<style>
    .table-purple {
        --bs-table-bg: #c4c1e0;
        color: rgb(80, 80, 80);
    }
    .table-light {
        --bs-table-bg: #ffdcd269;
        --bs-table-striped-bg: #fffdfddb;
    }
</style>

Pinturería Acuarela/Views/Product_Business/Index.cshtml
@model Pinturería_Acuarela.Product_Business

@{
    ViewBag.Title = "Stock";
}

<link href="~/Content/orders.css" rel="stylesheet" />
<link href="~/Content/notification.css" rel="stylesheet" />

<h1 class="text-center">Productos de @Model.Business.adress</h1>
<hr class="pb-3" />

@{ if (ViewBag.Message != null)
    {
        <div class="py-3 mb-5 @(ViewBag.Error == 1 ? "containerError1" : "")@(ViewBag.Error == 2 ? "containerError2" : "")@(ViewBag.Error == null ? "onlyMessage" : "")" id="notificationContainer">
            <div class="px-2 d-flex flex-row justify-content-between align-items-center">
                <div id="txtNotification">@ViewBag.Message</div>
                <button id="btnCloseNotification" type="button" aria-label="Cerrar">
                    <svg aria-hidden="true" height="16" viewBox="0 0 16 16" version="1.1" width="16" data-view-component="true" class="octicon octicon-x">
                        <path id="closeSVG" fill="rgb(0,75,180)" class="@(ViewBag.Error == 1 ? "error1" : "") @(ViewBag.Error == 2 ? "error2" : "") @(ViewBag.Error == null ? "onlyMessage" : "")" d="M3.72 3.72a.75.75 0 011.06 0L8 6.94l3.22-3.22a.75.75 0 111.06 1.06L9.06 8l3.22 3.22a.75.75 0 11-1.06 1.06L8 9.06l-3.22 3.22a.75.75 0 01-1.06-1.06L6.94 8 3.72 4.78a.75.75 0 010-1.06z"></path>
                    </svg>
                </button>
            </div>
        </div>
    }
}

@using (Html.BeginForm("Edit", "Product_Business", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.Hidden("id_product")
    @Html.Hidden("id_business", Model.Business.id)
    <!-- Modal -->
    <div class="modal modal-lg" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel"></h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
                </div>
                <div class="modal-body d-flex flex-column">
                    <div class="d-flex flex-column">
                        <div class="d-flex flex-row justify-content-center align-items-center">
                            <label class="pe-3">Stock existente: </label>
                            <div class='d-flex flex-row justify-content-center ps-3'>
                                <div class='value-button' id='decrease_stock' onclick='decreaseValue("stock")' value='Decrease Value'>-</div>
                                @Html.TextBoxFor(model => model.stock, null, new { @type = "number", @id = "stock", @class = "number" })
                                <div class='value-button' id='increase_stock' onclick='increaseValue("stock")' value='Increase Value'>+</div>
                            </div>
                        </div>
                        @Html.ValidationMessageFor(model => model.stock, null, new { @class = "text-center text-danger mb-4" })
                    </div>
                    <div class="d-flex flex-column">
                        <div class="d-flex flex-row justify-content-center align-items-center">
                            <label class="pe-3">Stock mínimo: </label>
                            <div class='d-flex flex-row justify-content-center ps-3'>
                                <div class='value-button' id='decrease_minimum_stock' onclick='decreaseValue("minimum_stock")' value='Decrease Value'>-</div>
                                @Html.TextBoxFor(model => model.minimum_stock, null, new { @type = "number", @id = "minimum_stock", @class = "number" })
                                <div class='value-button' id='increase_minimum_stock' onclick='increaseValue("minimum_stock")' value='Increase Value'>+</div>
                            </div>
                        </div>
                        @Html.ValidationMessageFor(model => model.minimum_stock, null, new { @class = "text-center text-danger mb-4" })
                    </div>
                </div>
                <div class="modal-footer d-flex flex-row justify-content-between">
                    <button id="btnSendForm" type="submit" class="btn" style="background-color: yellowgreen">Actualizar stock</button>
                    <button id="modalCerrar" type="button" class="btn btn-danger" data-bs-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
}

@using (Html.BeginForm("Delete", "Product_Business", FormMethod.Post))
{
    @Html.AntiForgeryToken();
    @Html.Hidden("id_business_delete", Model.Business.id)
    @Html.Hidden("id_product_delete")
    <!-- Modal -->
    <div class="modal fade" id="modalConfirmation" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="modalConfirmationLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="modalConfirmationLabel">Desasociar producto</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
                </div>
                <div class="modal-body">
                    ¿Seguro deseas desasociar este producto?
                </div>
                <div class="modal-footer d-flex justify-content-between justify-content-lg-end px-3">
                    <button type="submit" id="btnSendForm" class="btn me-lg-4" style="background-color: yellowgreen">Confirmar</button>
                    <button type="button" class="btn" style="background-color: crimson; color: white" data-bs-dismiss="modal">Cancelar</button>
                </div>
            </div>
        </div>
    </div>
}

<div class="container mt-4">

    @* Agregar productos *@
    <div class="sombra p-4 mb-5" style="border-radius: 20px; max-width: fit-content">
        <div id="searchContainer" class="d-flex justify-content-between">
            <a id="btnAdd" class="btn text-white" href="../../Product_Business/Create/@Model.Business.id" style="background-color: #6c7ae0">Asociar nuevo <i class="bi bi-plus-circle"></i></a>
        </div>
    </div>

    @* Tabla *@
    <table id='dataTable' class='container table table-light table-striped table-bordered table-hover pt-4'>
        <thead class='table-dark'>
            <tr>
                <td class='text-center sombra'></td>
                <td class='text-center d-flex flex-row sombra'>
                    <input class="form-control" id="txtSearch" placeholder="Cód. interno | Nombre" />
                    <button id="btnSearch" type="button" class="btn" style="color: white; background-color: #6c7ae0">
                        <i class="bi bi-search"></i>
                    </button>
                </td>
                <td class='text-center sombra'>@Html.DropDownList("id_brand", null, "Seleccionar", htmlAttributes: new { @class = "form-control", @id = "id_brand" })</td>
                <td class='text-center sombra'>@Html.DropDownList("id_category", null, "Seleccionar", htmlAttributes: new { @class = "form-control", @id = "id_category" })</td>
                <td class='text-center sombra'>@Html.DropDownList("id_subcategory", null, "Seleccionar", htmlAttributes: new { @class = "form-control", @id = "id_subcategory" })</td>
                <td class='text-center sombra'>@Html.DropDownList("id_color", null, "Seleccionar", htmlAttributes: new { @class = "form-control", @id = "id_color" })</td>
                <td class='text-center sombra'>@Html.DropDownList("id_capacity", null, "Seleccionar", htmlAttributes: new { @class = "form-control", @id = "id_capacity" })</td>
                <td class='text-center sombra'><input type="button" value="Filtrar" class="btn btn-outline-light" id="btnFilter" /></td>
                <td></td>
            </tr>
            <tr class='fw-bold'>
                <td class='text-center sombra'>Cód. Interno</td>
                <td class='text-center sombra'>Producto</td>
                <td class='text-center sombra'>Marca</td>
                <td class='text-center sombra'>Categoría</td>
                <td class='text-center sombra'>Subcategoría</td>
                <td class='text-center sombra'>Color</td>
                <td class='text-center sombra'>Capacidad</td>
                <td class='text-center sombra'>Stock</td>
                <td class='text-center sombra'>Acción</td>
            </tr>
        </thead>
        <tbody id="contentTable" class="sombra">
        </tbody>
    </table>
</div>

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/product_business_index.js"></script>
<script src="~/Scripts/notification.js"></script>